# Generated by Django 4.2.2 on 2023-10-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jan_ken_app', '0002_account_delete_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
